apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iurqbouxc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iurqbouxc-java-quarkus-gitops